name: beam_checkout_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  google_fonts: 6.1.0
  injectable: ^2.3.5
  injectable_generator: ^2.4.2
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
